# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:FwOKxRpvF9/MfGtiqvJvhtMyXVGo7klTlzFWZYXqk98=,iv:Sifrqm195eOoMpukJXxtQef17XHjp4mVuipUo9DJac0=,tag:fcppHsBjkbYroIMY9fHBZg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kyztntk9dvjf5906r72gyem06juk8p2lmujj74fkpk6wm9xpkq8q9dm55l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa3ZBd2tOZ1RKeEVIeHdP
        MkEvR3B4VVRqa2NiaG9NWXJCbElTNnBFZkJzCldINDRPcVBWdERIMUNaeHgwYnZQ
        RSt2ME4xTWdtRWZaVnZtangzTDN4UzAKLS0tIDlnQ1NvcEhERS9FY2JobzVlUHhr
        djIwU0dCdHU5RGxZWTlNb01PUnBRb1EKMmMgO8w3Bh/mMo+K/9q1xOKHWuWZVRLs
        S1V4T4kj6KFa6lKoR7fGdbK+qfTKhu/zr5VvVrt5I4KjZOLrPoPasw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-09T10:29:16Z"
  mac: ENC[AES256_GCM,data:MgHfYUITv84DJU9kip58Wf2zJyz9Ca5hT9nAGqkK0wpFfItiZuV0d6RKOK+dTlI6br1TDWWkYyby/YSKsa0+PTzZr//Zwn0MPL49sKZjVK7eRP6kCbIJgLjaSWQm0B9tsaDBGANddl/Fj/QvcjDWURCnf6iZiEwrdN8v38q2+gU=,iv:aiZViSTLDe6G6Rkwlc62TpLe/ac96Cp5pPTppmLUSwY=,tag:tCrduya5hO/bzM31f80ytA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
