# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:lyPXTx+46gUThxLaVnUCyRNIwH0Zl6R7E4+pTPflw04=,iv:K+QEj1rDS/H642kMeZzvwrO1ENIuh/bdyBXoxXU2tAg=,tag:DzCDDElh6cqG4lVYL5QDpA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kyztntk9dvjf5906r72gyem06juk8p2lmujj74fkpk6wm9xpkq8q9dm55l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S3o2YW5tNk5pSVRxY2dM
        TUQwUG0vR284aml6TnhselMvQVl0MlBSWEhNCjBFQzlPbWdkQTZxMUthNWpJb3dN
        Nkd1Z0h4VTNRdFk3QTdBNkxrRG03d2cKLS0tIG1ibFVZbFhIbVZSZndKQmdISUJ5
        OHkxWVVJdVB6SFUyWUtNeHpaYzk3U1kKCP5sTaPv1id74M9dGOPFvRzv/2NUV0u5
        CLi6DRWgVJmOA9De5fejiweYVjEJuCW4yxM1quDLatC72wiGSphg1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-09T10:34:39Z"
  mac: ENC[AES256_GCM,data:JlBdMrdgcFwZyTRHsp/YN9aHHY0Kncq3qfgBm/TCJkNMgU3P+HUTvNPpFJum90oxUEE9wwUzsN/dLWlJGsd5CoVzZ1u8xJaSDrBve7BmW9vueWxN3SuiF4Pf44kbToHlOTYu1LvIUGRM/rjc6pQsO8RpqfSGLxOZiVmh1v0ZCXY=,iv:BJ/FehsaUbH15Y8t+IA2Ua44xwb3vm3115TZqFDBzx0=,tag:QVdoZ4Whri57U6XtwvPJhA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
