# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:dOdOgXsOPvA+3OuyEUB6+uaR5J1lNh+kkQhF+o+9XhY=,iv:H8KXy+9vvZRjiZNfx88nIeGQ2t6qn7OEHEdJZfntjmE=,tag:X5PKO+5sq8QquEqmB/th5A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1mgxnvaq4zdcj7wxk960j6fqcxvj8k2suefqgmz6xth8sp0v9eveqvv83fp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eDVuOGpyM1FQT28yc0tn
        NGFGTmpBaVRRc0I0ZVIwNUV6Q0Z2OGFJV0EwClVvTmFKOFFkczlOWWVYSDl3UXZ0
        V1R4TjU4L0FBODJaTTZpVkM0ZlJ5L0EKLS0tIER2VTBPdzRFbThuRnBYcnU1aHJ3
        aEVIQk5DNFZVanZ4Q25zRjQvYWlZclkK7RqLdEVXpbPxzHrEM9RREtKWZIGsDuIB
        9xtQbreMVe2l7/6qnSLYNRnYGzYhgoc8x3wdH4Hmc6ATYlbgeBSHWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-17T09:50:39Z"
  mac: ENC[AES256_GCM,data:bhefl77MprHk22hx80PJEKuv3rn3AjGdxY59t1PeKtgV8pDNINs6cg+rjaRf2XHAYVk3CFMt2hXjmXXQ1kuc+BTNrOHTnecpvEs3wUvmtQowXm8mNMtbW8EXIoWac9F/Jqlj2ozcio67gkWQEB9AhUkAY8XKWnVONC/vnnXq+bY=,iv:5gwQEoVJRZrHcuXCdPBByNlgODGTIAKGyKxT5AI11cc=,tag:dVdDd3hU3nCnBZ7kM+RvXA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
