# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:G1nMjVnAz4EOjJo/5zkncmJinR5OXQ+GHiHDgpGHT4xnGgNPV66i4w==,iv:qLnsvGB7tYVFfHhqYJh43ClK0K26T6PfmRjRkvyTUNU=,tag:WjLL9fP5Nx/Y1KVRrLkDmg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1mgxnvaq4zdcj7wxk960j6fqcxvj8k2suefqgmz6xth8sp0v9eveqvv83fp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RkszcURvamNYeHl6MFc4
        S2lPeU5BN05nRVN3KzZxODlCOXFleVdPK2k0CmNTYUFoNkdzb1ZLOE1FVEc2RS9n
        cDI3eXI4dkVnUm95OWdyU1A4eU9CNUUKLS0tIEE4UkRQWllyOTVvcFNYUktGKzdV
        QUduMHhFQjQ3TUFCMFVPNzJLWHlxZU0KkanU8FrUHGwJz7j/ysPUObZcLxsIQuhw
        trIPUyc3xjyoH4XzL70mdOR1MP8Fycdq9clduSwNwm6nDB+Y7Ttztw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-16T12:03:03Z"
  mac: ENC[AES256_GCM,data:jUXPIngNvm+N+vZpR6w4/gX+ARjiqTtEqYTe+soxNjDwhxaB/hdYwEhduZSM5FwnTWpE4or1ILSR9Pr7rlCYJk3GK9P9LSi48s7iWHUDwTnh2aDxh8S+g9wHzPrL6HDsBLfylxjxAf4DMTMaiRk9Hh3p3CeSqkIhCyMGzBmZtNU=,iv:I+lRjfEMojgubJF+J1Q9QCTkWrWHEK9Y1CvzYHCVNK8=,tag:FXB8fvtLHlNVaTkckFu/ng==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
