apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_EXAMPLE: ENC[AES256_GCM,data:nWpTYWbK8zHcJFSiZPJ+MwGOO/BL0OyeU5KUybUoX11FIaTSGkbtJg/YJq5OY3E3w77D4o3Lqb0TXAo5TgnPZoQf1PKHSqw=,iv:sTlCYv3Wn5xf8MSIP55JJsApF34F2DkZcgATsMS+2ks=,tag:NOS/XBKGRuIe204S96gzsA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kyztntk9dvjf5906r72gyem06juk8p2lmujj74fkpk6wm9xpkq8q9dm55l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeTRDNk5MeGNTNkVnWmdy
        Kzd2VFdtZmtzT0p5K3A5ZFVaczd5QkFDMlhVCmUvd3BCWHdlZEprUUlXa1NkWmZZ
        TWM5REE0K3pCdXNzTE5QakExaXNvdEUKLS0tIEszQk1NbW5udWg0dU45bzdDN2pt
        TXlXMVo5ZGxTK2g5Z243SEdaSW5UOUkKVMN77N/olQUtuPSVenOnAwiKAoFRP2XX
        hlRdGQD4RpS5x0MIuxvULWNMo5+cVnJoQHyViVWwLnm/7drjmu6Y+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-09T10:29:16Z"
  mac: ENC[AES256_GCM,data:lTakNNihhWyFSABMdfEDd+lFHaHaXdP3fE7QW6BmOmXCBAncGOhSo96fjl1nmZ63Do5Re/a/mND/eAOSFdG4eCNPrph+8r3W0vEB4qeoUA7ITFla32XTyWgkCKVyiwyTRqiMO+0kdulsvciW8cv3DLUs6cherErVU2ZLG+epTIg=,iv:EJJ1coVMfXRq5VQDE0S6ilmY+SROjcenV+iBEkN3SeM=,tag:1fiRJfvdGCZCEf0kUHM8/Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
