apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_EXAMPLE: ENC[AES256_GCM,data:/oCKrBZFWof1IKTE5kbBqyUoPprOFm4h+s/GI0cLxSOPzxJ13ki4yhRrXEAqN+NMlALSSajhBvfNxz7uVehryMv147DCd6k=,iv:KunPTRpdv3tcwr1AhD9FpFAciG40DFoqmhI5VCbun+M=,tag:cPf9A3/ljdZ1dalmLEnPzQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kyztntk9dvjf5906r72gyem06juk8p2lmujj74fkpk6wm9xpkq8q9dm55l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUCsvZEtUcHRHd21Gdkxl
        WGNnMHRZQThib25DN3ljd29vbmRWbkhjSEIwCnJDQ3hPZ093Y3BtaTVtUm5pbFQ0
        Q1NzU25NSE5JbEtsdGlod3EzbUh0ODAKLS0tIEZvUjAyNmJjTXZUZ1lEcEpZQnRM
        WWxRc09rNkVDaFByMXNQRDVsKzhMU0kK4hA+lnQ5C5z9hpkBPlcZH0FNUF82AEH6
        9MLwGYwpLwZ4/qRhEdMuJhepko+AR+cRpQ97fBub9w46HJTgnyPIFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-09T10:34:39Z"
  mac: ENC[AES256_GCM,data:qS/q88dGTUiPmen18qQImZEnixTA0b60netcX3nCfD6vGvu+6lZ8oSEaWVDhAe4mbnbdBEEvD8To0DXhibRhJTisFXx/y1Fr93ahz4Z2+2c3Iam/W7fuWK0qxHKKlnMBPuM3GwqMFDsaiY1w2iXilmonCo8/cafmEWfMJ/bWxc8=,iv:a/JLHTsXMpWuinbjV0275xDwRZR5GPNENSOdse8fcP8=,tag:tOmgLaD5fDSKB8SweCHe4A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
