apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:DVe+i+P3a7BHJE8=,iv:sUE3MWEbueg6EXyls6l1TDiixW/XRohUHvFGzI2wnRA=,tag:RSEAMj+a/mKNrX8Ye93IXA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ARKw8RBJOkkMIBWU/NSpsRRU3WQs0/zoBiXhY8ApSxd915Ja,iv:M4Ka3h+3e9LkF8X2PX/GeJB+au1Vhd63yGKek0HGSJs=,tag:H4tKgWvU6oNt7A55NjyfzQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1mgxnvaq4zdcj7wxk960j6fqcxvj8k2suefqgmz6xth8sp0v9eveqvv83fp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYklUVFoweXprNGJYMldu
        Ky9BTWdnRlhOM2pleVV6YmdxMUNvOENlTlI4CkJURDRZNkNpRlgwaUVLbUF4Q0NR
        bHN6bDRDZ1UvOFE2cEpVczZoK2lOQncKLS0tICsxK1RDWHl1YTBTZXNxcHpkb05W
        Unc1eFd4bHhGWkV2R3RWOHJCR3orSEUKNmWCgdKWuK6BHUghylL7c9vQnOPNz9jW
        ijG53IvhItF0X8xoXKs+k60WQRRjgOZSac8L4vSDuPFAYwUcqozmdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-16T14:07:11Z"
  mac: ENC[AES256_GCM,data:WS7iZyLikfD+rQc6B/sBh6viJ/HmL655BPiEz93SY7wVklpBkk8TXemc624kdTAuq16Su1YJtSOYIIhU4IFrwoGgK1PO9MqhAeAxqU5llZE6aojWTJDjNl7Ylk/TwcbqkFNB6lvZ/nR30RAh9s6J9kYKCBJm4CjwBpdKkiViMho=,iv:97U+JxKXHDvXGpqQoFWkg1XXch+HO+DUzy0AEYrdKQ0=,tag:m16I7n+cgwnkHvag96FB5g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
