---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-minimal
  namespace: ns-demopod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-minimal
  template:
    metadata:
      labels:
        app: nginx-minimal
    spec:
      containers:
        - name: nginx
          image: nginx:latest
